name: called-preset-pr
on:
  workflow_call:
    secrets:
      token:
        required: true
permissions: write-all
jobs:
  set-assignees:
    runs-on: ubuntu-latest
    if: ${{ toJSON(github.event.pull_request.assignees) == '[]' && github.actor != 'dependabot[bot]' }}
    steps:
      - name: Set assignees
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.token }}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [`${{ github.actor }}`]
            });
