name: preset-pr
on:
  pull_request:
    types: [opened, reopened]
run-name: ${{ github.workflow }} (${{ github.ref_name }})
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions: write-all
jobs:
  call-preset-pr:
    uses: ./.github/workflows/called-preset-pr.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
